### PR TITLE
Update README.md with site using addon in production

### PR DESCRIPTION
**Pull request by declanramsay**
Adding my website which is now using this addon in prod.

### CODE REVIEW

**Comment by ardalann** [comment]
Awesome! Thanks, Declan!
Any feedback about the add-on? Was the setup easy enough?

**Comment by declanramsay** [comment]
Setup was pretty straightforward, I had a few issues building locally but I think that was related to the local version of npm I was running (5.0.0). Shifted to the latest 4 version + everything was fine.

**Comment by ardalann** [comment]
Yes, as it turns out npm5 is not prod-ready at all.
Glad you found the setup straightforward. Let me know if you have any other feedback.

**Comment by ardalann** [comment]
@thelucideffect I just noticed every URL on your website is responding with the prerendered HOMEPAGE. Seems like you've set up the server so that it always responds with the root-level `/index.html`. Was that intentional?
ember-cli-prerender creates a separate index.html per page. I'd recommend setting up the server so it responds with the proper index.html based on the URL path (which is the normal behaviour on static web servers).

**Pull request merged**
